update crew set crewno = 'S01',CrewName = 'Elephants' where GangNo = 'REAADDNURE'
update crew set crewno = 'S03',CrewName = 'Rooikat' where GangNo = 'REAADDNURB'
update crew set crewno = 'S04',CrewName = 'Flamingo' where GangNo = 'REAGAANURB'
update crew set crewno = 'S05',CrewName = 'Hawks' where GangNo = 'REACDDNURA'
update crew set crewno = 'S06',CrewName = 'Nyala' where GangNo = 'REAGABNURB'
update crew set crewno = 'S07',CrewName = 'Vultures' where GangNo = 'REAADANURA'
update crew set crewno = 'S09',CrewName = 'Waterbuck' where GangNo = 'REAGADNURD'
update crew set crewno = 'S10',CrewName = 'Cats' where GangNo = 'REABCANURA'
update crew set crewno = 'S11',CrewName = 'Wildebeest' where GangNo = 'REAMAANURB'
update crew set crewno = 'S12',CrewName = 'Rhino''s' where GangNo = 'REABAANURB'
update crew set crewno = 'S13',CrewName = 'Cows' where GangNo = 'REABCANURB'
update crew set crewno = 'S14',CrewName = 'Ostrich' where GangNo = 'REABBBNURA'
update crew set crewno = 'S15',CrewName = 'Ox' where GangNo = 'REABBANURA'
update crew set crewno = 'S16',CrewName = 'Sea Lion' where GangNo = 'REABCBNURA'
update crew set crewno = 'S17',CrewName = 'Wild Dogs' where GangNo = 'REABBANURB'
update crew set crewno = 'S18',CrewName = 'Zebra' where GangNo = 'REAMAANURD'
update crew set crewno = 'S19',CrewName = 'Husky' where GangNo = 'REAMAANURA'
update crew set crewno = 'S20',CrewName = 'Leopards' where GangNo = 'REAADANURE'
update crew set crewno = 'S21',CrewName = 'Wasps' where GangNo = 'REACDANURB'
update crew set crewno = 'S22',CrewName = 'Chillies' where GangNo = 'REABBANURC'
update crew set crewno = 'S24',CrewName = 'Bulls' where GangNo = 'REAGADNURC'
update crew set crewno = 'S25',CrewName = 'Jackal' where GangNo = 'REACAANURB'
update crew set crewno = 'S26',CrewName = 'Panthers' where GangNo = 'REAMBANURA'
update crew set crewno = 'S27',CrewName = 'Tigers - W-Wze' where GangNo = 'REAGBGNURA'
update crew set crewno = 'S28',CrewName = 'Caterpillar' where GangNo = 'REACCCNURC'
update crew set crewno = 'S29',CrewName = 'Meerkats - W-Wze' where GangNo = 'REAGAANURZ'
update crew set crewno = 'S30',CrewName = 'Hyena' where GangNo = 'REACAANURA'
update crew set crewno = 'S31',CrewName = 'Crocodiles' where GangNo = 'REACAENURA'
update crew set crewno = 'S32',CrewName = 'Fish Eagles' where GangNo = 'REACAANURC'
update crew set crewno = 'S34',CrewName = 'Sharks' where GangNo = 'REAGABNURA'
update crew set crewno = 'S35',CrewName = 'Cobras' where GangNo = 'REAGBBNURA'
update crew set crewno = 'S36',CrewName = 'Porcupine' where GangNo = 'REAGBANURA'
update crew set crewno = 'S37',CrewName = 'BushBuck' where GangNo = 'REAGBCNURA'
update crew set crewno = 'S38',CrewName = 'Cheethas' where GangNo = 'REAGADNURB'
update crew set crewno = 'S39',CrewName = 'Bear' where GangNo = 'REAGAANURA'
update crew set crewno = 'S40',CrewName = 'Dolphins' where GangNo = 'REAGADNURA'
update crew set crewno = 'S41',CrewName = 'Eland' where GangNo = 'REACDDNURC'
update crew set crewno = 'S42',CrewName = 'Pumas' where GangNo = 'REAGBDNURA'
update crew set crewno = 'S43',CrewName = 'Lions' where GangNo = 'REACDDNURD'
update crew set crewno = 'S44',CrewName = 'Dragons' where GangNo = 'REAGBENURA'
update crew set crewno = 'S45',CrewName = 'Hippos' where GangNo = 'REACABNURA'
update crew set crewno = 'S46',CrewName = 'Springboks' where GangNo = 'REACBBNURA'
update crew set crewno = 'S47',CrewName = 'Giraffe' where GangNo = 'REACDDNURE'
update crew set crewno = 'S48',CrewName = 'Jaguar' where GangNo = 'REACCCNURA'
update crew set crewno = 'S51',CrewName = 'Fox' where GangNo = 'REACAENURB'
update crew set crewno = 'S52',CrewName = 'Scorpions' where GangNo = 'REACADNURA'
update crew set crewno = 'S53',CrewName = 'Eagles' where GangNo = 'REAADANURC'
update crew set crewno = 'S54',CrewName = 'Impala' where GangNo = 'REAADDNURA'
update crew set crewno = 'S55',CrewName = 'Camel' where GangNo = 'REAMAANURC'
update crew set crewno = 'S60',CrewName = '' where GangNo = 'REAMDANURA'
update crew set crewno = 'D01',CrewName = 'Juventus  X/C' where GangNo = 'REUCAANURA'
update crew set crewno = 'D02',CrewName = 'Wits TW' where GangNo = 'REUCAANURC'
update crew set crewno = 'D03',CrewName = 'BloemfonteinCeltics Hlge' where GangNo = 'REUCABNURA'
update crew set crewno = 'D04',CrewName = 'SuperSportUnited  XC' where GangNo = 'REUCBANURA'
update crew set crewno = 'D05',CrewName = 'InterMilan  BH' where GangNo = 'REUCBBNURA'
update crew set crewno = 'D06',CrewName = 'Tottenham' where GangNo = 'REUCBBNURC'
update crew set crewno = 'D07',CrewName = 'NathiLions Winze' where GangNo = 'REUCBCNURA'
update crew set crewno = 'D08',CrewName = 'OrlandoPirates' where GangNo = 'REUCABNURB'
update crew set crewno = 'D09',CrewName = 'Germany BH 1' where GangNo = 'REUHAANURJ'
update crew set crewno = 'D10',CrewName = 'Hungry Lions' where GangNo = 'REUHAANURC'
update crew set crewno = 'D11',CrewName = 'Manchester United XC' where GangNo = 'REUHAANURE'
update crew set crewno = 'D12',CrewName = 'Sundowns XC' where GangNo = 'REUHAANURF'
update crew set crewno = 'D13',CrewName = 'Manchester City TW2' where GangNo = 'REUHAANURI'
update crew set crewno = 'D14',CrewName = 'Amazulu XC' where GangNo = 'REUHABNURA'
update crew set crewno = 'D15',CrewName = 'Barcelona Rse' where GangNo = 'REUHACNURA'
update crew set crewno = 'D16',CrewName = 'Matlama Hlge' where GangNo = 'REUKAANURA'
update crew set crewno = 'D17',CrewName = 'Santos Hlge' where GangNo = 'REUKAANURD'
update crew set crewno = 'D18',CrewName = 'Maritzburg United RAW' where GangNo = 'REUKAANURC'
update crew set crewno = 'D19',CrewName = 'Liverpool Hlge' where GangNo = 'REULAANURA'
update crew set crewno = 'D20',CrewName = 'Kaizer Chiefs X/C' where GangNo = 'REULAANURI'
update crew set crewno = 'D21 ',CrewName = 'MorokaSwallows TW' where GangNo = 'REULAANURB'
update crew set crewno = 'D22',CrewName = 'Brazil X/C' where GangNo = 'REULAANURG'
update crew set crewno = 'D23',CrewName = 'Real Madrid X/C' where GangNo = 'REULAANURC'
update crew set crewno = 'D24',CrewName = 'Arsenal  Winze' where GangNo = 'REULAANURD'
update crew set crewno = 'D25',CrewName = 'Chelsea TW' where GangNo = 'REULAANURH'
update crew set crewno = 'D26',CrewName = 'Germany BH 2' where GangNo = 'REUHAANURK'
update crew set crewno = 'D27',CrewName = 'Ajax  TW' where GangNo = 'REULAANURF'
update crew set crewno = 'D28',CrewName = 'Chippa United BH1' where GangNo = 'REULAANURE'
update crew set crewno = 'D29',CrewName = 'Free Sate Stars Hlge' where GangNo = 'REULAANURM'
update crew set crewno = 'D30',CrewName = 'Baroka  TW' where GangNo = 'REULAANURL'
update crew set crewno = 'D31',CrewName = 'Thanda Royal' where GangNo = 'REUKAANURB'
update crew set crewno = 'D32',CrewName = 'D32' where GangNo = 'REULAANURK'
