Insert Into Problem ([ProblemID],[ProblemGroupCode],[EnquirerID],[Description],[ExtraInfo],[Valid],[EmailGroup],[HQCat])
Values (N'A1',N'11.Services',N'PRO',N'Inadquate air supply/pressure',0,N'Y',NULL,N'Maintenance Issues')
,(N'B1',N'4.Blasting',N'PRO',N'Misfire',0,N'Y',NULL,N'Good / Poor Production')
,(N'B2',N'4.Blasting',N'PRO',N'ASG behind',0,N'Y',NULL,N'Good / Poor Production')
,(N'B3',N'4.Blasting',N'PRO',N'Sliping / Bad Breaking',0,N'Y',NULL,N'Good / Poor Production')
,(N'B4',N'4.Blasting',N'PRO',N'Cut Offs',0,N'Y',NULL,N'Good / Poor Production')
,(N'BO',N'12.Trackless',N'PRO',N'Belt O.O.O',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'C1',N'5.Cleaning',N'PRO',N'Panel choked',0,N'Y',NULL,N'Good / Poor Production')
,(N'C2',N'5.Cleaning',N'PRO',N'Stope tip full',0,N'Y',NULL,N'Good / Poor Production')
,(N'C3',N'5.Cleaning',N'PRO',N'ASG choked',0,N'Y',NULL,N'Good / Poor Production')
,(N'C4',N'5.Cleaning',N'PRO',N'Winch forward move',0,N'Y',NULL,N'Delays in projects')
,(N'C5',N'5.Cleaning',N'PRO',N'No rigs in ASG/panel',0,N'Y',NULL,N'Other safety related issues')
,(N'C6',N'5.Cleaning',N'PRO',N'Faceshape',0,N'Y',NULL,N'Other safety related issues')
,(N'C7',N'5.Cleaning',N'PRO',N'Big rocks',0,N'Y',NULL,N'Good / Poor Production')
,(N'C8',N'5.Cleaning',N'CON',N'Nightshift Cleaning Incomplete',0,N'Y',N'',N'Good / Poor Production')
,(N'C9',N'5.Cleaning',N'PRO',N'Cut Offs',0,N'Y',NULL,N'Good / Poor Production')
,(N'D1',N'3.Mining',N'PRO',N'Pillar cutting',0,N'Y',NULL,N'Lack of IMS')
,(N'D10',N'3.Mining',N'PRO',N'Equipping',0,N'Y',NULL,N'Lack of IMS')
,(N'D11',N'3.Mining',N'PRO',N'Establishing Face',0,N'Y',NULL,N'Lack of IMS')
,(N'D12',N'3.Mining',N'PRO',N'Sliping',0,N'Y',NULL,N'Good / Poor Production')
,(N'D2',N'3.Mining',N'PRO',N'Pillar holing',0,N'Y',NULL,N'Other safety related issues')
,(N'D3',N'3.Mining',N'PRO',N'Re-raise',0,N'Y',NULL,N'Lack of IMS')
,(N'D4',N'3.Mining',N'PRO',N'Cover drilling',0,N'Y',NULL,N'Other safety related issues')
,(N'D5',N'3.Mining',N'PRO',N'Poor planning (eg of mat. or equip)',0,N'Y',NULL,N'Good / Poor Production')
,(N'D6',N'3.Mining',N'PRO',N'Incomplete/slow drilling',0,N'Y',NULL,N'Good / Poor Production')
,(N'D8',N'3.Mining',N'PRO',N'Leads & Lags',0,N'Y',NULL,N'Good / Poor Production')
,(N'D9',N'3.Mining',N'PRO',N'Sweeping back area',0,N'Y',NULL,N'Good / Poor Production')
,(N'DR',N'12.Trackless',N'PRO',N'Drill Rig Breakdown',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'E1',N'1.Safety & Env.',N'PRO',N'Methane intersection',0,N'Y',N'',N'Other safety related issues')
,(N'E10',N'1.Safety & Env.',N'PRO',N'Safety stoppage: Crew',0,N'Y',N'',N'Special safty intervention training')
,(N'E11',N'1.Safety & Env.',N'PRO',N'Safety stoppage: Line Mngmt',0,N'Y',N'',N'Special safty intervention training')
,(N'E12',N'1.Safety & Env.',N'PRO',N'Safety stoppage: Safety Off',0,N'Y',N'',N'Special safty intervention training')
,(N'E13',N'1.Safety & Env.',N'PRO',N'Safety stoppage: Other',0,N'Y',N'',N'Other safety related issues')
,(N'E14',N'1.Safety & Env.',N'PRO',N'Workstop  n/std: Line Mngmt',0,N'Y',N'',N'Other safety related issues')
,(N'E15',N'1.Safety & Env.',N'PRO',N'Workstop  n/std: Safety Off',0,N'Y',N'',N'Other safety related issues')
,(N'E16',N'1.Safety & Env.',N'PRO',N'Workstop  n/std: Crew',0,N'Y',N'',N'Other safety related issues')
,(N'E17',N'1.Safety & Env.',N'PRO',N'Workstop  n/std: Other',0,N'Y',N'',N'Other safety related issues')
,(N'E2',N'1.Safety & Env.',N'PRO',N'Fire',0,N'Y',N'',N'Ground conditions (safety reasons)')
,(N'E3',N'1.Safety & Env.',N'PRO',N'Inadequate ventilation',0,N'Y',N'',N'Other safety related issues')
,(N'E4',N'1.Safety & Env.',N'PRO',N'Water intersection  ',0,N'Y',N'',N'Other safety related issues')
,(N'E5',N'1.Safety & Env.',N'PRO',N'Section 54',0,N'Y',N'',N'Section 54 stoppages')
,(N'E6',N'1.Safety & Env.',N'PRO',N'Fatal',0,N'Y',N'',N'Fatality stoppages & ass losses')
,(N'E7',N'1.Safety & Env.',N'PRO',N'Lost Time Injury',0,N'Y',N'',N'Fatality stoppages & ass losses')
,(N'E8',N'1.Safety & Env.',N'PRO',N'Section 55',0,N'Y',N'',N'Section 54 stoppages')
,(N'E9',N'1.Safety & Env.',N'PRO',N'U/Ground Injury',0,N'Y',NULL,N'Good / Poor Production')
,(N'G1',N'10.Geology',N'PRO',N'FOG',0,N'Y',NULL,N'Ground conditions (safety reasons)')
,(N'G3',N'10.Geology',N'PRO',N'Rockburst',0,N'Y',NULL,N'Ground conditions (safety reasons)')
,(N'G4',N'10.Geology',N'PRO',N'Stopped on geological feature',0,N'Y',NULL,N'Ground conditions (non-safety related)')
,(N'G5',N'10.Geology',N'PRO',N'Awaiting Info',0,N'Y',NULL,N'Good / Poor Production')
,(N'G6',N'10.Geology',N'PRO',N'Bad Ground Conditions',0,N'Y',NULL,N'Good / Poor Production')
,(N'L1',N'6.Logistics',N'PRO',N'Shaft tips full',0,N'Y',NULL,N'Good / Poor Production')
,(N'L10',N'6.Logistics',N'PRO',N'Belt Failure',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'L2',N'6.Logistics',N'PRO',N'Loco electrical failure',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'L3',N'6.Logistics',N'PRO',N'Loco mechanical failure (eg brake failure)',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'L4',N'6.Logistics',N'PRO',N'Flat loco batteries',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'L5',N'6.Logistics',N'PRO',N'Loader out of order',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'L6',N'6.Logistics',N'PRO',N'Derailment',0,N'Y',NULL,N'Other B/d and plant failure')
,(N'L7',N'6.Logistics',N'PRO',N'Mudrush',0,N'Y',NULL,N'Infrastructure failures')
,(N'L8',N'6.Logistics',N'PRO',N'Shortage of tramming equipment',0,N'Y',NULL,N'Infrastructure failures')
,(N'L9',N'6.Logistics',N'PRO',N'Orepass hung up (obstructions in it)',0,N'Y',NULL,N'Infrastructure failures')
,(N'LHD',N'12.Trackless',N'PRO',N'LHD Breakdown',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'M1',N'9.Materials',N'PRO',N'Timber shortage',0,N'Y',NULL,N'Lack of supply (timber,tires)')
,(N'M2',N'9.Materials',N'PRO',N'Other materials/equpiment shortage',0,N'Y',NULL,N'Lack of supply (timber,tires)')
,(N'MB',N'12.Trackless',N'PRO',N'Machine Breakdown',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'MD',N'12.Trackless',N'PRO',N'Machine Damage',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'MS',N'12.Trackless',N'PRO',N'Machine Service',0,N'Y',NULL,N'Maintenance Issues')
,(N'N1',N'7.Labour',N'PRO',N'Work stoppage (eg tools down/strike)',0,N'Y',NULL,N'Strikes')
,(N'N2',N'7.Labour',N'PRO',N'Labour under compliment',0,N'Y',NULL,N'Skilled labour shortages')
,(N'N3',N'7.Labour',N'PRO',N'Labour absent',0,N'Y',NULL,N'Absenteeism')
,(N'N4',N'7.Labour',N'PRO',N'Shift down late',0,N'Y',NULL,N'Skilled labour shortages')
,(N'O1',N'13.Other',N'PRO',N'Other',0,N'N',NULL,N'')
,(N'P1',N'11.Services',N'PRO',N'Power failure',0,N'Y',NULL,N'Infrastructure failures')
,(N'Q1',N'8.Equip. Fail',N'PRO',N'Drilling equipment (eg drills, face equipment)',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'Q2',N'8.Equip. Fail',N'PRO',N'Cleaning equipment (eg winches, scrapers)',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'Q3',N'8.Equip. Fail',N'PRO',N'Mining equipment (eg mono-ropes)',0,N'Y',NULL,N'Maintenance Issues')
,(N'Q4',N'8.Equip. Fail',N'PRO',N'Logistics equipment (eg non-loco like rails)',0,N'Y',NULL,N'Infrastructure failures')
,(N'Q5',N'8.Equip. Fail',N'PRO',N'Other engineering equipment (eg small vent fans)',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'Q6',N'8.Equip. Fail',N'PRO',N'Chargingup equipment failure',0,N'Y',NULL,N'Maintenance Issues')
,(N'Q7',N'8.Equip. Fail',N'PRO',N'Roof bolt failure',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'Q8',N'8.Equip. Fail',N'PRO',N'Pump failure',0,N'Y',NULL,N'Breakdowns (vehicles etc)')
,(N'Q9',N'8.Equip. Fail',N'PRO',N'Electrical Failure',0,N'Y',NULL,N'Good / Poor Production')
,(N'S1',N'2.Support',N'PRO',N'Inadequate/incomplete support',0,N'Y',NULL,N'Special safty intervention training')
,(N'S2',N'2.Support',N'PRO',N'Support blasted out',0,N'Y',NULL,N'Special safty intervention training')
,(N'S3',N'2.Support',N'PRO',N'Installing additional support',0,N'Y',NULL,N'Ground conditions (safety reasons)')
,(N'S4',N'2.Support',N'PRO',N'No Backfill',0,N'Y',NULL,N'Other safety related issues')
,(N'TR',N'7.Labour',N'PRO',N'Training',0,N'Y',NULL,N'New crews')
,(N'W1',N'11.Services',N'PRO',N'Inadequate water supply/pressure',0,N'Y',NULL,N'Infrastructure failures')
,(N'W2',N'11.Services',N'PRO',N'Hoisting Breakdown',0,N'Y',NULL,N'Good / Poor Production')